Refactor code into functions

diff --git a/os-release b/os-release
--- a/os-release
+++ b/os-release
@@ -2,15 +2,26 @@
 
 OS_RELEASE_FILE=/etc/os-release
 
-if [ ! -f "$OS_RELEASE_FILE" ]; then
-	echo "ERROR: No information (no such file: $OS_RELEASE_FILE)." 1>&2
-	exit 1
-fi
+function check_os_release_file() {
+	if [ ! -f "$OS_RELEASE_FILE" ]; then
+		echo "ERROR: No information (no such file: $OS_RELEASE_FILE)." 1>&2
+		exit 1
+	fi
+}
 
-IFS='='
-while read name value; do
-	name=$(sed -e 's/\(.*\)/\L\1/g; s/_/\ /g; s/^./\U&/g; s/\ ./\U&/g' <<< $name)
-	value=$(sed -e 's/"//g' <<< $value)
-	printf "%16s: %s\n" $name $value
-done < $OS_RELEASE_FILE
+function print_os_release_information() {
+	IFS='='
+	while read name value; do
+		name=$(sed -e 's/\(.*\)/\L\1/g; s/_/\ /g; s/^./\U&/g; s/\ ./\U&/g' <<< $name)
+		value=$(sed -e 's/"//g' <<< $value)
+		printf "%16s: %s\n" $name $value
+	done < $OS_RELEASE_FILE
+}
+
+function main() {
+	check_os_release_file
+	print_os_release_information
+}
+
+main "$@"
 
